[[rocRAND]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c565b6e353eb2ec9345ac55ba0f2d6be3444bea"
libc = "glibc"
os = "linux"

    [[rocRAND.download]]
    sha256 = "a1d611c5f73d39923c7c58aeead02156e820be1b4219746f5ed1b2d1350fe416"
    url = "https://github.com/JuliaBinaryWrappers/rocRAND_jll.jl/releases/download/rocRAND-v4.2.0+0/rocRAND.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rocRAND]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3225185e8c8b9010b6f99df4448a72ceb13f294"
libc = "musl"
os = "linux"

    [[rocRAND.download]]
    sha256 = "1edc7cf5a8c446b2db64097d3fbdeb6a13ef96c0643e759ccbe3fa0086281df7"
    url = "https://github.com/JuliaBinaryWrappers/rocRAND_jll.jl/releases/download/rocRAND-v4.2.0+0/rocRAND.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
