[[rocRAND]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f32e80b256ed82bae6982288b859e244a36479d"
libc = "glibc"
os = "linux"

    [[rocRAND.download]]
    sha256 = "905badbeb1eba344f953597f588e3f267dc0827c85303f81e439fd192b6f32d6"
    url = "https://github.com/JuliaBinaryWrappers/rocRAND_jll.jl/releases/download/rocRAND-v5.2.3+1/rocRAND.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
[[rocRAND]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b263df8f38399302cd3d89908f6da13bbe310f79"
libc = "musl"
os = "linux"

    [[rocRAND.download]]
    sha256 = "477f8a116fdbfaa443a6fb6015fa4fd60196e760eb7f3211d2f9fd468c99a6d9"
    url = "https://github.com/JuliaBinaryWrappers/rocRAND_jll.jl/releases/download/rocRAND-v5.2.3+1/rocRAND.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"
